server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: 'app-logs'
    static_configs:
      - targets: ['localhost']
        labels:
          job: app
          __path__: /home/rgui/www/obs-demo/app/logs/*.log 